/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevConsoleRouteImport } from './routes/dev-console'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as HrisRouteImport } from './routes/hris'
import { Route as MenuAccessRouteImport } from './routes/menu-access'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffForgotPinRouteImport } from './routes/staff/forgot-pin'
import { Route as StaffHistoryRouteImport } from './routes/staff/history'
import { Route as StaffInboxRouteImport } from './routes/staff/inbox'
import { Route as StaffProfileRouteImport } from './routes/staff/profile'
import { Route as StaffRequestRouteImport } from './routes/staff/request'
import { Route as StaffSetupRouteImport } from './routes/staff/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevConsoleRoute = DevConsoleRouteImport.update({
  id: '/dev-console',
  path: '/dev-console',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrisRoute = HrisRouteImport.update({
  id: '/hris',
  path: '/hris',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuAccessRoute = MenuAccessRouteImport.update({
  id: '/menu-access',
  path: '/menu-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffForgotPinRoute = StaffForgotPinRouteImport.update({
  id: '/staff/forgot-pin',
  path: '/staff/forgot-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffHistoryRoute = StaffHistoryRouteImport.update({
  id: '/staff/history',
  path: '/staff/history',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInboxRoute = StaffInboxRouteImport.update({
  id: '/staff/inbox',
  path: '/staff/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/staff/profile',
  path: '/staff/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRequestRoute = StaffRequestRouteImport.update({
  id: '/staff/request',
  path: '/staff/request',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSetupRoute = StaffSetupRouteImport.update({
  id: '/staff/setup',
  path: '/staff/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-console': typeof DevConsoleRoute
  '/directory': typeof DirectoryRoute
  '/finance': typeof FinanceRoute
  '/hris': typeof HrisRoute
  '/menu-access': typeof MenuAccessRoute
  '/settings': typeof SettingsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/forgot-pin': typeof StaffForgotPinRoute
  '/staff/history': typeof StaffHistoryRoute
  '/staff/inbox': typeof StaffInboxRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/request': typeof StaffRequestRoute
  '/staff/setup': typeof StaffSetupRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-console': typeof DevConsoleRoute
  '/directory': typeof DirectoryRoute
  '/finance': typeof FinanceRoute
  '/hris': typeof HrisRoute
  '/menu-access': typeof MenuAccessRoute
  '/settings': typeof SettingsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/forgot-pin': typeof StaffForgotPinRoute
  '/staff/history': typeof StaffHistoryRoute
  '/staff/inbox': typeof StaffInboxRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/request': typeof StaffRequestRoute
  '/staff/setup': typeof StaffSetupRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-console': typeof DevConsoleRoute
  '/directory': typeof DirectoryRoute
  '/finance': typeof FinanceRoute
  '/hris': typeof HrisRoute
  '/menu-access': typeof MenuAccessRoute
  '/settings': typeof SettingsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/forgot-pin': typeof StaffForgotPinRoute
  '/staff/history': typeof StaffHistoryRoute
  '/staff/inbox': typeof StaffInboxRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/request': typeof StaffRequestRoute
  '/staff/setup': typeof StaffSetupRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ats'
    | '/dashboard'
    | '/dev-console'
    | '/directory'
    | '/finance'
    | '/hris'
    | '/menu-access'
    | '/settings'
    | '/staff/dashboard'
    | '/staff/forgot-pin'
    | '/staff/history'
    | '/staff/inbox'
    | '/staff/profile'
    | '/staff/request'
    | '/staff/setup'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ats'
    | '/dashboard'
    | '/dev-console'
    | '/directory'
    | '/finance'
    | '/hris'
    | '/menu-access'
    | '/settings'
    | '/staff/dashboard'
    | '/staff/forgot-pin'
    | '/staff/history'
    | '/staff/inbox'
    | '/staff/profile'
    | '/staff/request'
    | '/staff/setup'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/ats'
    | '/dashboard'
    | '/dev-console'
    | '/directory'
    | '/finance'
    | '/hris'
    | '/menu-access'
    | '/settings'
    | '/staff/dashboard'
    | '/staff/forgot-pin'
    | '/staff/history'
    | '/staff/inbox'
    | '/staff/profile'
    | '/staff/request'
    | '/staff/setup'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsRoute: typeof AtsRoute
  DashboardRoute: typeof DashboardRoute
  DevConsoleRoute: typeof DevConsoleRoute
  DirectoryRoute: typeof DirectoryRoute
  FinanceRoute: typeof FinanceRoute
  HrisRoute: typeof HrisRoute
  MenuAccessRoute: typeof MenuAccessRoute
  SettingsRoute: typeof SettingsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffForgotPinRoute: typeof StaffForgotPinRoute
  StaffHistoryRoute: typeof StaffHistoryRoute
  StaffInboxRoute: typeof StaffInboxRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffRequestRoute: typeof StaffRequestRoute
  StaffSetupRoute: typeof StaffSetupRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-console': {
      id: '/dev-console'
      path: '/dev-console'
      fullPath: '/dev-console'
      preLoaderRoute: typeof DevConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hris': {
      id: '/hris'
      path: '/hris'
      fullPath: '/hris'
      preLoaderRoute: typeof HrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-access': {
      id: '/menu-access'
      path: '/menu-access'
      fullPath: '/menu-access'
      preLoaderRoute: typeof MenuAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/forgot-pin': {
      id: '/staff/forgot-pin'
      path: '/staff/forgot-pin'
      fullPath: '/staff/forgot-pin'
      preLoaderRoute: typeof StaffForgotPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/history': {
      id: '/staff/history'
      path: '/staff/history'
      fullPath: '/staff/history'
      preLoaderRoute: typeof StaffHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/inbox': {
      id: '/staff/inbox'
      path: '/staff/inbox'
      fullPath: '/staff/inbox'
      preLoaderRoute: typeof StaffInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/staff/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/request': {
      id: '/staff/request'
      path: '/staff/request'
      fullPath: '/staff/request'
      preLoaderRoute: typeof StaffRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/setup': {
      id: '/staff/setup'
      path: '/staff/setup'
      fullPath: '/staff/setup'
      preLoaderRoute: typeof StaffSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsRoute: AtsRoute,
  DashboardRoute: DashboardRoute,
  DevConsoleRoute: DevConsoleRoute,
  DirectoryRoute: DirectoryRoute,
  FinanceRoute: FinanceRoute,
  HrisRoute: HrisRoute,
  MenuAccessRoute: MenuAccessRoute,
  SettingsRoute: SettingsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffForgotPinRoute: StaffForgotPinRoute,
  StaffHistoryRoute: StaffHistoryRoute,
  StaffInboxRoute: StaffInboxRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffRequestRoute: StaffRequestRoute,
  StaffSetupRoute: StaffSetupRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
